import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type TourAndante } from './tourAndante';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Export Module - Andante
 * Id: a12955a6-33ac-404a-b098-695ef274e9fb
 * Codename: export_module___andante
 */
export type ExportModuleAndante = IContentItem<{
    /**
     * Export to CSV (custom)
     * Required: false
     * Id: 48b4e832-1fd1-4981-8f87-f7746743ef7b
     * Codename: export_to_csv
     */
    exportToCsv: Elements.CustomElement;

    /**
     * Tours to Export (modular_content)
     * Required: false
     * Id: 3003c448-101a-4f18-80ba-063b11ee43b7
     * Codename: tours_to_export
     */
    toursToExport: Elements.LinkedItemsElement<TourAndante>;
}>;
