import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Export Module - Brightwater
 * Id: 46cdf8d6-a184-44e2-8677-9642b322dce2
 * Codename: export_module___andante__copy_
 */
export type ExportModuleBrightwater = IContentItem<{
    /**
     * Export to CSV (custom)
     * Required: false
     * Id: 777ca70c-cacf-4ae8-b05f-ce803595d17d
     * Codename: export_to_csv
     */
    exportToCsv: Elements.CustomElement;

    /**
     * Tours to Export (modular_content)
     * Required: false
     * Id: dc08370d-6ece-48b1-82db-ebc147ed0419
     * Codename: tours_to_export
     */
    toursToExport: Elements.LinkedItemsElement<ExportModuleBrightwater>;
}>;
