import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Excursion } from './excursion';
import { type Hotel } from './hotel';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Tour
 * Id: 6a42abf2-4651-4cbb-bf59-e0995d442de8
 * Codename: tour
 */
export type Tour_SJ = IContentItem<{
    /**
     * Export Tour_SJ (custom)
     * Required: false
     * Id: 187c79ff-8347-4ce8-950a-ca3b5facb689
     * Codename: export_tour
     */
    exportTour: Elements.CustomElement;
 

    /**
     * Images (asset)
     * Required: false
     * Id: 37720700-dc2e-4070-a64d-d15b2c296f12
     * Codename: images
     */
    images: Elements.AssetsElement;
 

    /**
     * Tour type (multiple_choice) 
     * Codename: tour_type
     */
    tourType: Elements.MultipleChoiceElement;

    /**
     * Tour Intro (rich_text)
     * Required: true
     * Id: 6623fbb4-aec7-4cd6-88a6-bcbee95b151e
     * Codename: tour_intro
     */
    tourIntro: Elements.RichTextElement;

    

    /**
     * Tour Title (text)
     * Required: true
     * Id: 876d8a43-5c12-4c3a-a09d-79b0487862ee
     * Codename: tour_title
     */
    tourTitle: Elements.TextElement;

    /**
     * What's Included (rich_text)
     * Required: true
     * Id: a1a40563-6186-4f52-834b-e09a0344ef51
     * Codename: untitled_rich_text
     */
    untitledRichText: Elements.RichTextElement;
}>;
