import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Tour Manager Guide Lecturer Biography
 * Id: 14153ce3-83c5-4bae-9669-896c68a2c0df
 * Codename: tour_manager_guide_lecturer_biography
 */
export type TourManagerGuideLecturerBiography = IContentItem<{
    /**
     * Biography (rich_text)
     * Required: true
     * Id: 0b63863d-9ead-4a56-ae7d-49974691df7f
     * Codename: biography
     */
    biography: Elements.RichTextElement;

    /**
     * Name (text)
     * Required: true
     * Id: 2b4d50d4-c32b-492a-89ee-3b43126e5692
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * Title (text)
     * Required: true
     * Id: 69a127d6-3558-4c48-b06d-f1350f549986
     * Codename: title
     */
    title: Elements.TextElement;
}>;
