import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Tour - Brightwater
 * Id: 468045cd-b317-4320-b1f1-c58184b75d0a
 * Codename: tour___andante__copy_
 */
export type TourBrightwater = IContentItem<{
    /**
     * Export (custom)
     * Required: false
     * Id: 54cb7253-d084-4b8d-9684-cef0255998b1
     * Codename: export
     */
    export: Elements.CustomElement;

    /**
     * Guest Quotes (rich_text)
     * Required: false
     * Id: c804fc71-19cd-4891-a880-0d74e62c3c65
     * Codename: guest_quotes
     */
    guestQuotes: Elements.RichTextElement;

    /**
     * Tour Manager Box (rich_text)
     * Required: false
     * Id: 132738a4-b8cf-4544-9c96-8563ea549a41
     * Codename: guides
     */
    guides: Elements.RichTextElement;

    /**
     * Images (asset)
     * Required: false
     * Id: 828aacba-fef8-4964-8237-2119540054f0
     * Codename: images
     */
    images: Elements.AssetsElement;

    /**
     * Tour Code (rich_text)
     * Required: true
     * Id: 38121dc7-325c-48a2-9850-78012523883d
     * Codename: tour_code
     */
    tourCode: Elements.RichTextElement;

    /**
     * Tour duration in days (number)
     * Required: true
     * Id: 80475fe4-09fb-4854-aa0c-aca179e4abb4
     * Codename: tour_duration_in_days
     */
    tourDurationInDays: Elements.NumberElement;

    /**
     * Tour Extra Info (rich_text)
     * Required: false
     * Id: ef19038d-4974-4522-b07a-d4a9c16f4c10
     * Codename: tour_extra_info
     */
    tourExtraInfo: Elements.RichTextElement;

    /**
     * Tour Highlights (rich_text)
     * Required: false
     * Id: fa85d119-42c2-49af-9d1e-d66577aa6d12
     * Codename: tour_highlights
     */
    tourHighlights: Elements.RichTextElement;

    /**
     * Tour Intro (rich_text)
     * Required: false
     * Id: ebc2514c-e2a0-42d1-9a20-eab9c9af1240
     * Codename: tour_intro
     */
    tourIntro: Elements.RichTextElement;

    /**
     * Tour Itinerary (rich_text)
     * Required: true
     * Id: 284339e5-967a-4d2e-86c0-2be4813d8b90
     * Codename: tour_itinerary
     */
    tourItinerary: Elements.RichTextElement;

    /**
     * Tour Title (rich_text)
     * Required: true
     * Id: a9a6ee1d-389a-4370-b32f-4b42416a59e0
     * Codename: tour_title
     */
    tourTitle: Elements.RichTextElement;

    /**
     * What's Included (rich_text)
     * Required: false
     * Id: 046f4245-2e83-4928-8d8d-e120775fdb4d
     * Codename: what_s_included
     */
    whatSIncluded: Elements.RichTextElement;
}>;
