/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const contentTypes = {
    /**
     * Export Module   Andante
     */
    export_module___andante: {
        codename: 'export_module___andante',
        id: 'a12955a6-33ac-404a-b098-695ef274e9fb',
        externalId: undefined,
        name: 'Export Module - Andante',
        elements: {
            /**
             * Export to CSV (custom)
             */
            export_to_csv: {
                codename: 'export_to_csv',
                id: '48b4e832-1fd1-4981-8f87-f7746743ef7b',
                externalId: undefined,
                name: 'Export to CSV',
                required: false,
                type: 'custom'
            },

            /**
             * Tours to Export (modular_content)
             */
            tours_to_export: {
                codename: 'tours_to_export',
                id: '3003c448-101a-4f18-80ba-063b11ee43b7',
                externalId: undefined,
                name: 'Tours to Export',
                required: false,
                type: 'modular_content'
            }
        }
    },

    /**
     * Export Module   Brightwater
     */
    export_module___andante__copy_: {
        codename: 'export_module___andante__copy_',
        id: '46cdf8d6-a184-44e2-8677-9642b322dce2',
        externalId: undefined,
        name: 'Export Module - Brightwater',
        elements: {
            /**
             * Export to CSV (custom)
             */
            export_to_csv: {
                codename: 'export_to_csv',
                id: '777ca70c-cacf-4ae8-b05f-ce803595d17d',
                externalId: undefined,
                name: 'Export to CSV',
                required: false,
                type: 'custom'
            },

            /**
             * Tours to Export (modular_content)
             */
            tours_to_export: {
                codename: 'tours_to_export',
                id: 'dc08370d-6ece-48b1-82db-ebc147ed0419',
                externalId: undefined,
                name: 'Tours to Export',
                required: false,
                type: 'modular_content'
            }
        }
    },

    /**
     * Tour   Andante
     */
    tour___andante: {
        codename: 'tour___andante',
        id: '720bd8ff-46b6-47cd-b42a-fb7b225516c4',
        externalId: undefined,
        name: 'Tour - Andante',
        elements: {
            /**
             * Export (custom)
             */
            untitled_custom_element: {
                codename: 'untitled_custom_element',
                id: '06a35080-26d6-4c3d-9dd1-d101d5a22caa',
                externalId: undefined,
                name: 'Export',
                required: false,
                type: 'custom'
            },

            /**
             * Guest Quotes (rich_text)
             */
            guest_quotes: {
                codename: 'guest_quotes',
                id: '6b6ac89c-68b2-4e74-a78c-865546049684',
                externalId: undefined,
                name: 'Guest Quotes',
                required: false,
                type: 'rich_text'
            },

            /**
             * Guides (rich_text)
             */
            guides: {
                codename: 'guides',
                id: 'c6a245bd-ef9c-4ed8-93a0-3060828469d0',
                externalId: undefined,
                name: 'Guides',
                required: false,
                type: 'rich_text'
            },

            /**
             * Images (asset)
             */
            images: {
                codename: 'images',
                id: '7dcb115e-a95f-4844-91c5-0b992619fc6d',
                externalId: undefined,
                name: 'Images',
                required: false,
                type: 'asset'
            },

            /**
             * Tour Code (rich_text)
             */
            tour_code: {
                codename: 'tour_code',
                id: 'c7532c54-21de-4b68-90fd-afed0457838c',
                externalId: undefined,
                name: 'Tour Code',
                required: true,
                type: 'rich_text'
            },

            /**
             * Tour duration in days (number)
             */
            tour_duration_in_days: {
                codename: 'tour_duration_in_days',
                id: '206560cc-993f-43de-b5b6-ccdca9476d48',
                externalId: undefined,
                name: 'Tour duration in days',
                required: true,
                type: 'number'
            },

            /**
             * Tour Extra Info (rich_text)
             */
            tour_extra_info: {
                codename: 'tour_extra_info',
                id: '00ad3df8-0788-442f-b249-f86350d57886',
                externalId: undefined,
                name: 'Tour Extra Info',
                required: false,
                type: 'rich_text'
            },

            /**
             * Tour Highlights (rich_text)
             */
            tour_highlights: {
                codename: 'tour_highlights',
                id: 'ee815359-e234-4c6f-b87c-1d5e62b1e962',
                externalId: undefined,
                name: 'Tour Highlights',
                required: true,
                type: 'rich_text'
            },

            /**
             * Tour Intro (rich_text)
             */
            tour_intro: {
                codename: 'tour_intro',
                id: '643d4a87-b375-4044-ab0c-156dd73fcb91',
                externalId: undefined,
                name: 'Tour Intro',
                required: false,
                type: 'rich_text'
            },

            /**
             * Tour Itinerary (rich_text)
             */
            tour_itinerary: {
                codename: 'tour_itinerary',
                id: '93b7298c-4640-4260-a94a-177b756c991a',
                externalId: undefined,
                name: 'Tour Itinerary',
                required: true,
                type: 'rich_text'
            },

            /**
             * Tour Subheading (rich_text)
             */
            tour_subheading: {
                codename: 'tour_subheading',
                id: '2b657678-8242-4570-810b-750416094954',
                externalId: undefined,
                name: 'Tour Subheading',
                required: false,
                type: 'rich_text'
            },

            /**
             * Tour Summary (rich_text)
             */
            tour_summary: {
                codename: 'tour_summary',
                id: '3f18ba6a-db7a-4770-a6f3-0bda104d0661',
                externalId: undefined,
                name: 'Tour Summary',
                required: false,
                type: 'rich_text'
            },

            /**
             * Tour Title (rich_text)
             */
            tour_title: {
                codename: 'tour_title',
                id: '2d1af372-8a3f-4e7b-ade1-8e822f3e33d1',
                externalId: undefined,
                name: 'Tour Title',
                required: true,
                type: 'rich_text'
            },

            /**
             * What s Included (rich_text)
             */
            what_s_included: {
                codename: 'what_s_included',
                id: '1cf08bb9-15cc-4577-b5b5-43cfe187ed8f',
                externalId: undefined,
                name: "What's Included",
                required: false,
                type: 'rich_text'
            }
        }
    },

    /**
     * Tour   Brightwater
     */
    tour___andante__copy_: {
        codename: 'tour___andante__copy_',
        id: '468045cd-b317-4320-b1f1-c58184b75d0a',
        externalId: undefined,
        name: 'Tour - Brightwater',
        elements: {
            /**
             * Export (custom)
             */
            export: {
                codename: 'export',
                id: '54cb7253-d084-4b8d-9684-cef0255998b1',
                externalId: undefined,
                name: 'Export',
                required: false,
                type: 'custom'
            },

            /**
             * Guest Quotes (rich_text)
             */
            guest_quotes: {
                codename: 'guest_quotes',
                id: 'c804fc71-19cd-4891-a880-0d74e62c3c65',
                externalId: undefined,
                name: 'Guest Quotes',
                required: false,
                type: 'rich_text'
            },

            /**
             * Guides (rich_text)
             */
            guides: {
                codename: 'guides',
                id: '132738a4-b8cf-4544-9c96-8563ea549a41',
                externalId: undefined,
                name: 'Guides',
                required: false,
                type: 'rich_text'
            },

            /**
             * Images (asset)
             */
            images: {
                codename: 'images',
                id: '828aacba-fef8-4964-8237-2119540054f0',
                externalId: undefined,
                name: 'Images',
                required: false,
                type: 'asset'
            },

            /**
             * Tour Code (rich_text)
             */
            tour_code: {
                codename: 'tour_code',
                id: '38121dc7-325c-48a2-9850-78012523883d',
                externalId: undefined,
                name: 'Tour Code',
                required: true,
                type: 'rich_text'
            },

            /**
             * Tour duration in days (number)
             */
            tour_duration_in_days: {
                codename: 'tour_duration_in_days',
                id: '80475fe4-09fb-4854-aa0c-aca179e4abb4',
                externalId: undefined,
                name: 'Tour duration in days',
                required: true,
                type: 'number'
            },

            /**
             * Tour Extra Info (rich_text)
             */
            tour_extra_info: {
                codename: 'tour_extra_info',
                id: 'ef19038d-4974-4522-b07a-d4a9c16f4c10',
                externalId: undefined,
                name: 'Tour Extra Info',
                required: false,
                type: 'rich_text'
            },

            /**
             * Tour Highlights (rich_text)
             */
            tour_highlights: {
                codename: 'tour_highlights',
                id: 'fa85d119-42c2-49af-9d1e-d66577aa6d12',
                externalId: undefined,
                name: 'Tour Highlights',
                required: false,
                type: 'rich_text'
            },

            /**
             * Tour Intro (rich_text)
             */
            tour_intro: {
                codename: 'tour_intro',
                id: 'ebc2514c-e2a0-42d1-9a20-eab9c9af1240',
                externalId: undefined,
                name: 'Tour Intro',
                required: false,
                type: 'rich_text'
            },

            /**
             * Tour Itinerary (rich_text)
             */
            tour_itinerary: {
                codename: 'tour_itinerary',
                id: '284339e5-967a-4d2e-86c0-2be4813d8b90',
                externalId: undefined,
                name: 'Tour Itinerary',
                required: true,
                type: 'rich_text'
            },

            /**
             * Tour Title (rich_text)
             */
            tour_title: {
                codename: 'tour_title',
                id: 'a9a6ee1d-389a-4370-b32f-4b42416a59e0',
                externalId: undefined,
                name: 'Tour Title',
                required: true,
                type: 'rich_text'
            },

            /**
             * What s Included (rich_text)
             */
            what_s_included: {
                codename: 'what_s_included',
                id: '046f4245-2e83-4928-8d8d-e120775fdb4d',
                externalId: undefined,
                name: "What's Included",
                required: false,
                type: 'rich_text'
            }
        }
    },

    /**
     * Tour Manager Guide Lecturer Biography
     */
    tour_manager_guide_lecturer_biography: {
        codename: 'tour_manager_guide_lecturer_biography',
        id: '14153ce3-83c5-4bae-9669-896c68a2c0df',
        externalId: undefined,
        name: 'Tour Manager Guide Lecturer Biography',
        elements: {
            /**
             * Biography (rich_text)
             */
            biography: {
                codename: 'biography',
                id: '0b63863d-9ead-4a56-ae7d-49974691df7f',
                externalId: undefined,
                name: 'Biography',
                required: true,
                type: 'rich_text'
            },

            /**
             * Name (text)
             */
            name: {
                codename: 'name',
                id: '2b4d50d4-c32b-492a-89ee-3b43126e5692',
                externalId: undefined,
                name: 'Name',
                required: true,
                type: 'text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '69a127d6-3558-4c48-b06d-f1350f549986',
                externalId: undefined,
                name: 'Title',
                required: true,
                type: 'text'
            }
        }
    }
} as const;
