/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const taxonomies = {
    /**
     * Images
     */
    desert_tours: {
        codename: 'desert_tours',
        id: '03ecd8a3-9fdd-4789-bc9e-7085b5283849',
        externalId: undefined,
        name: 'Images',
        terms: {
            albania: {
                codename: 'albania',
                id: 'd5636afb-7bbb-453b-a4e7-b6338423c9b9',
                externalId: undefined,
                name: 'Albania',
                terms: {}
            },
            albania___montenegro___kosovo: {
                codename: 'albania___montenegro___kosovo',
                id: 'f1670749-e8e8-4fa0-8e22-8e9c9b24b559',
                externalId: undefined,
                name: 'Albania & Montenegro & Kosovo',
                terms: {}
            },
            algeria: {
                codename: 'algeria',
                id: '1eb08772-7cfd-4609-9c45-23f82b3f22ac',
                externalId: undefined,
                name: 'Algeria',
                terms: {}
            },
            archaeology: {
                codename: 'archaeology',
                id: '2b583271-9ba8-4728-aada-f407ba4999b0',
                externalId: undefined,
                name: 'Archaeology',
                terms: {}
            },
            argentina: {
                codename: 'argentina',
                id: '7ea0be5b-f3d7-43fc-aeac-ba03c06f6558',
                externalId: undefined,
                name: 'Argentina',
                terms: {}
            },
            armenia___georgia: {
                codename: 'armenia___georgia',
                id: '40d2a678-34d1-4ecb-a42d-f779886b2b24',
                externalId: undefined,
                name: 'Armenia & Georgia',
                terms: {}
            },
            australia: {
                codename: 'australia',
                id: 'a4c82803-8a00-4ba0-84f3-ed12366bcde4',
                externalId: undefined,
                name: 'Australia',
                terms: {}
            },
            austria: {
                codename: 'austria',
                id: 'ba67f559-8c3b-4d91-8510-6b435d67d12d',
                externalId: undefined,
                name: 'Austria',
                terms: {}
            },
            barbados: {
                codename: 'barbados',
                id: '2a1a2a84-b68f-41b4-a22d-2d522f676d96',
                externalId: undefined,
                name: 'Barbados',
                terms: {}
            },
            belgium: {
                codename: 'belgium',
                id: 'e595ad6f-26f8-4437-88cb-bcd70f913d2e',
                externalId: undefined,
                name: 'Belgium',
                terms: {}
            },
            bhutan: {
                codename: 'bhutan',
                id: 'fcb38b0d-df2f-415c-b073-1db87c23f147',
                externalId: undefined,
                name: 'Bhutan',
                terms: {}
            },
            borneo: {
                codename: 'borneo',
                id: '530d2326-e8d1-46a0-b3c2-a7795f0ee9eb',
                externalId: undefined,
                name: 'Borneo',
                terms: {}
            },
            brazil: {
                codename: 'brazil',
                id: 'd96f5221-155f-41d5-bf79-88cf5af30013',
                externalId: undefined,
                name: 'Brazil',
                terms: {}
            },
            california: {
                codename: 'california',
                id: 'b2f5a556-a4ca-4def-8cb8-6113ea669769',
                externalId: undefined,
                name: 'California',
                terms: {}
            },
            canada: {
                codename: 'canada',
                id: 'f00964ac-e390-44c7-b8a3-734d7bb4a768',
                externalId: undefined,
                name: 'Canada',
                terms: {}
            },
            chile: {
                codename: 'chile',
                id: '0854fbc1-257f-4f79-8a6a-8d3ced2b505d',
                externalId: undefined,
                name: 'Chile',
                terms: {}
            },
            costa_rica: {
                codename: 'costa_rica',
                id: '2383695a-6e26-45d6-873f-be8c1f0f5b42',
                externalId: undefined,
                name: 'Costa Rica',
                terms: {}
            },
            croatia: {
                codename: 'croatia',
                id: '5bb9cae6-c0e0-4683-87b0-1895c6e8e62a',
                externalId: undefined,
                name: 'Croatia',
                terms: {}
            },
            cruise: {
                codename: 'cruise',
                id: 'e08e94b4-6b7f-459a-85b5-f3d714760b7c',
                externalId: undefined,
                name: 'Cruise',
                terms: {}
            },
            cuba: {
                codename: 'cuba',
                id: '9bdb9a6c-b890-40e3-9024-9bae05e39d9a',
                externalId: undefined,
                name: 'Cuba',
                terms: {}
            },
            cyprus: {
                codename: 'cyprus',
                id: '395a87e5-44a6-4785-8572-65410ab2ee7c',
                externalId: undefined,
                name: 'Cyprus',
                terms: {}
            },
            czechia: {
                codename: 'czechia',
                id: 'b0f1542d-34e4-4146-bd60-aaac14568030',
                externalId: undefined,
                name: 'Czechia',
                terms: {}
            },
            denmark: {
                codename: 'denmark',
                id: '62f3536e-fd16-4748-b1bf-2b88e1ee4224',
                externalId: undefined,
                name: 'Denmark',
                terms: {}
            },
            desert: {
                codename: 'desert',
                id: '31e0c30e-0454-4822-bac9-6e1a21baf598',
                externalId: undefined,
                name: 'Desert',
                terms: {}
            },
            dunes: {
                codename: 'dunes',
                id: '0a15fb02-4966-4790-ad70-354cc86e6192',
                externalId: undefined,
                name: 'Dunes',
                terms: {}
            },
            ecuador: {
                codename: 'ecuador',
                id: 'c9823e90-7f76-4e1f-8fd6-98d7f7bb3a69',
                externalId: undefined,
                name: 'Ecuador',
                terms: {}
            },
            egypt: {
                codename: 'egypt',
                id: 'c303ad08-d39a-4daa-88be-5c9c287874f6',
                externalId: undefined,
                name: 'Egypt',
                terms: {}
            },
            england: {
                codename: 'england',
                id: 'f0a041eb-2e8e-487b-8519-a0291bd5fc60',
                externalId: undefined,
                name: 'England',
                terms: {}
            },
            essentials: {
                codename: 'essentials',
                id: '466267be-f286-4b9c-87be-9d884527fd3f',
                externalId: undefined,
                name: 'Essentials',
                terms: {}
            },
            experience_day: {
                codename: 'experience_day',
                id: 'eeb386ab-38e6-4d14-8be3-5e3039e94115',
                externalId: undefined,
                name: 'Experience Day',
                terms: {}
            },
            flower_shows: {
                codename: 'flower_shows',
                id: 'b2a4e0d6-66e6-4998-9ecc-82788852190b',
                externalId: undefined,
                name: 'Flower Shows',
                terms: {}
            },
            france: {
                codename: 'france',
                id: 'add92ee4-0996-45e2-b5aa-c1bd2f825da8',
                externalId: undefined,
                name: 'France',
                terms: {}
            },
            gardens: {
                codename: 'gardens',
                id: '6360b92d-3d28-4fbd-b6c4-fbbe82d894e8',
                externalId: undefined,
                name: 'Gardens',
                terms: {}
            },
            germany: {
                codename: 'germany',
                id: 'ae762d18-1d92-49ae-8a5e-4f115d63f829',
                externalId: undefined,
                name: 'Germany',
                terms: {}
            },
            gozo: {
                codename: 'gozo',
                id: '5ed45d06-d34a-4f4d-bf6f-790ad0e8b305',
                externalId: undefined,
                name: 'Gozo',
                terms: {}
            },
            greece: {
                codename: 'greece',
                id: '2f64bfad-aa74-4552-9bc3-449b414c1d18',
                externalId: undefined,
                name: 'Greece',
                terms: {}
            },
            grenada: {
                codename: 'grenada',
                id: 'c0e91f8a-5c5f-4931-94de-d8970c0cc785',
                externalId: undefined,
                name: 'Grenada',
                terms: {}
            },
            guadeloupe: {
                codename: 'guadeloupe',
                id: '57f7e50f-033c-4a69-9da9-37b02a290473',
                externalId: undefined,
                name: 'Guadeloupe',
                terms: {}
            },
            guatemala__honduras___belize: {
                codename: 'guatemala__honduras___belize',
                id: '4c406e2f-4197-4873-999e-bbc79b978017',
                externalId: undefined,
                name: 'Guatemala, Honduras & Belize',
                terms: {}
            },
            history: {
                codename: 'history',
                id: '6b852c55-9398-4d86-a1c4-9ab6327b4891',
                externalId: undefined,
                name: 'History',
                terms: {}
            },
            hungary: {
                codename: 'hungary',
                id: '9d9ab84d-fc74-4233-a497-24958ca2d31b',
                externalId: undefined,
                name: 'Hungary',
                terms: {}
            },
            iceland: {
                codename: 'iceland',
                id: '5b346f97-0e5a-4465-a106-36a66ef5434f',
                externalId: undefined,
                name: 'Iceland',
                terms: {}
            },
            india: {
                codename: 'india',
                id: '66619609-7f78-43cf-84c4-f9a86f2ed372',
                externalId: undefined,
                name: 'India',
                terms: {}
            },
            ireland: {
                codename: 'ireland',
                id: '00f03d19-ff33-4ccc-9d33-a591c3eafbb5',
                externalId: undefined,
                name: 'Ireland',
                terms: {}
            },
            israel__palestine: {
                codename: 'israel__palestine',
                id: '9a12b427-1ebf-4bc3-8b00-99ded14edf3b',
                externalId: undefined,
                name: 'Israel, Palestine',
                terms: {}
            },
            istanbul: {
                codename: 'istanbul',
                id: 'ea569c51-f898-4b8b-ba28-d185a9bda9a7',
                externalId: undefined,
                name: 'Istanbul',
                terms: {}
            },
            italy: {
                codename: 'italy',
                id: '617c051b-43e5-418a-959a-8b59e0778f31',
                externalId: undefined,
                name: 'Italy',
                terms: {}
            },
            japan: {
                codename: 'japan',
                id: '4a6c4292-c029-4fb0-a919-20bef2c1aa19',
                externalId: undefined,
                name: 'Japan',
                terms: {}
            },
            jordan: {
                codename: 'jordan',
                id: 'b3c47603-60dc-4872-bf05-f7da047c699a',
                externalId: undefined,
                name: 'Jordan',
                terms: {}
            },
            lebanon: {
                codename: 'lebanon',
                id: 'c4ea19be-003e-4d78-b416-b79fb67424a0',
                externalId: undefined,
                name: 'Lebanon',
                terms: {}
            },
            long_haul: {
                codename: 'long_haul',
                id: 'a1c6f86b-0bc7-4145-bfa6-aacec2184396',
                externalId: undefined,
                name: 'Long-haul',
                terms: {}
            },
            madagascar: {
                codename: 'madagascar',
                id: 'e845135c-faec-41bd-8c33-6836b4c35bdd',
                externalId: undefined,
                name: 'Madagascar',
                terms: {}
            },
            malaysia: {
                codename: 'malaysia',
                id: '74de27c5-c91e-4ba9-a67d-836bac518c95',
                externalId: undefined,
                name: 'Malaysia',
                terms: {}
            },
            malta___gozo: {
                codename: 'malta___gozo',
                id: '67cb63a3-dad5-464c-8909-41e59b2284d8',
                externalId: undefined,
                name: 'Malta',
                terms: {}
            },
            mauritius: {
                codename: 'mauritius',
                id: '94cc5750-7b57-4b08-bc83-43b4096b57af',
                externalId: undefined,
                name: 'Mauritius',
                terms: {}
            },
            mexico: {
                codename: 'mexico',
                id: '54aa1abe-ff97-4fde-a069-d7fa1220aab4',
                externalId: undefined,
                name: 'Mexico',
                terms: {}
            },
            mongolia: {
                codename: 'mongolia',
                id: 'd590fcf1-5140-4426-8385-314355052f7e',
                externalId: undefined,
                name: 'Mongolia',
                terms: {}
            },
            montenegro: {
                codename: 'montenegro',
                id: 'c3f83807-9aae-4c94-b51d-20e357367ba7',
                externalId: undefined,
                name: 'Montenegro',
                terms: {}
            },
            morocco: {
                codename: 'morocco',
                id: 'abda617a-8ebe-4561-a397-29abe5ce0ca6',
                externalId: undefined,
                name: 'Morocco',
                terms: {}
            },
            nepal: {
                codename: 'nepal',
                id: 'df050877-f450-47e0-9fa1-84b8aaa1d5bd',
                externalId: undefined,
                name: 'Nepal',
                terms: {}
            },
            netherlands: {
                codename: 'netherlands',
                id: '2f768527-4e21-433a-b905-4ee1783f27a9',
                externalId: undefined,
                name: 'Netherlands',
                terms: {}
            },
            new_zealand: {
                codename: 'new_zealand',
                id: '2d5be887-070e-4722-a701-df2d4a37ad5d',
                externalId: undefined,
                name: 'New Zealand',
                terms: {}
            },
            northern_ireland: {
                codename: 'northern_ireland',
                id: '0de1e53e-36f3-4477-ad21-06603ef4e2ba',
                externalId: undefined,
                name: 'Northern Ireland',
                terms: {}
            },
            norway__sweden: {
                codename: 'norway__sweden',
                id: 'e73f7309-bd3b-4739-8aad-f49763621d17',
                externalId: undefined,
                name: 'Norway, Sweden',
                terms: {}
            },
            oman: {
                codename: 'oman',
                id: 'c988d462-9491-46d5-942f-13a6d4439075',
                externalId: undefined,
                name: 'Oman',
                terms: {}
            },
            overseas_garden_tours: {
                codename: 'overseas_garden_tours',
                id: 'c4b6c449-d5e2-4a76-876d-6a2b8b9c3813',
                externalId: undefined,
                name: 'Overseas Garden Tours',
                terms: {}
            },
            overseas_special_interest: {
                codename: 'overseas_special_interest',
                id: 'f5acea9b-b700-40ae-91af-d9707ccef597',
                externalId: undefined,
                name: 'Overseas Special Interest',
                terms: {}
            },
            pakistan: {
                codename: 'pakistan',
                id: 'da1d59af-b72f-4ffe-b015-724853c58e83',
                externalId: undefined,
                name: 'Pakistan',
                terms: {}
            },
            paris: {
                codename: 'paris',
                id: '03927edc-fe63-4e99-abb5-d4767de8f61e',
                externalId: undefined,
                name: 'Paris',
                terms: {}
            },
            peru: {
                codename: 'peru',
                id: '26c4ddd7-ba71-46f9-af31-d220ab3b5eb2',
                externalId: undefined,
                name: 'Peru',
                terms: {}
            },
            portugal: {
                codename: 'portugal',
                id: '48eab21c-d8dd-4941-a7dd-136a41f9ae5c',
                externalId: undefined,
                name: 'Portugal',
                terms: {}
            },
            premium: {
                codename: 'premium',
                id: 'c5beac40-a39f-4fd9-9d65-3444e58c1b3e',
                externalId: undefined,
                name: 'Premium',
                terms: {}
            },
            pyramids: {
                codename: 'pyramids',
                id: '563f09c6-4622-4fa1-8294-2f7b69eab1cb',
                externalId: undefined,
                name: 'Pyramids',
                terms: {}
            },
            rail: {
                codename: 'rail',
                id: 'a8d5c4e9-d120-4e33-91e1-d28537a2e2bd',
                externalId: undefined,
                name: 'Rail',
                terms: {}
            },
            saint_lucia: {
                codename: 'saint_lucia',
                id: '30de151c-873c-4704-96c6-84e36005a907',
                externalId: undefined,
                name: 'Saint Lucia',
                terms: {}
            },
            saudi_arabia: {
                codename: 'saudi_arabia',
                id: 'a29559d9-db29-4562-86a9-6fe82dfd1c42',
                externalId: undefined,
                name: 'Saudi Arabia',
                terms: {}
            },
            scenic_scottish_tours: {
                codename: 'scenic_scottish_tours',
                id: 'fc1fa5d1-7dcf-4622-b649-184080e973ce',
                externalId: undefined,
                name: 'Scenic Scottish Tours',
                terms: {}
            },
            scotland: {
                codename: 'scotland',
                id: 'cc46d8eb-f09a-4e24-9a81-5620258301e3',
                externalId: undefined,
                name: 'Scotland',
                terms: {}
            },
            serbia: {
                codename: 'serbia',
                id: 'b60c87ec-2ac5-4b74-9f38-2bbe55854b4d',
                externalId: undefined,
                name: 'Serbia',
                terms: {}
            },
            singapore: {
                codename: 'singapore',
                id: 'b19cd7ab-1c6d-43ab-b2ab-6b34ea417c71',
                externalId: undefined,
                name: 'Singapore',
                terms: {}
            },
            south_africa: {
                codename: 'south_africa',
                id: '2a9f5009-b7b3-4063-983a-ce9985602798',
                externalId: undefined,
                name: 'South Africa',
                terms: {}
            },
            spain: {
                codename: 'spain',
                id: '44495379-935a-4957-979b-f533782f0b78',
                externalId: undefined,
                name: 'Spain',
                terms: {}
            },
            special_interest: {
                codename: 'special_interest',
                id: '504fb304-346e-47ff-9364-95a6a926fc9c',
                externalId: undefined,
                name: 'Special Interest',
                terms: {}
            },
            sri_lanka: {
                codename: 'sri_lanka',
                id: '3330fbb2-b515-4472-968a-e432d547b6e8',
                externalId: undefined,
                name: 'Sri Lanka',
                terms: {}
            },
            study_days: {
                codename: 'study_days',
                id: 'fda038e0-004c-4118-ad0d-5957a7657ae1',
                externalId: undefined,
                name: 'Study Days',
                terms: {}
            },
            sudan: {
                codename: 'sudan',
                id: 'a1c82c32-2316-498c-839e-bd054142b18a',
                externalId: undefined,
                name: 'Sudan',
                terms: {}
            },
            switzerland: {
                codename: 'switzerland',
                id: '549bf994-9306-4aec-a8b3-900ed8f5ffd0',
                externalId: undefined,
                name: 'Switzerland',
                terms: {}
            },
            tanzania: {
                codename: 'tanzania',
                id: '5dfe6bf6-9720-4cff-b8a9-ea4e078bdea3',
                externalId: undefined,
                name: 'Tanzania',
                terms: {}
            },
            tunisia: {
                codename: 'tunisia',
                id: '537700e8-9b01-4480-8859-86390ac2d777',
                externalId: undefined,
                name: 'Tunisia',
                terms: {}
            },
            turkey: {
                codename: 'turkey',
                id: '5659d85a-487e-4375-a2c7-545cda7d3bfd',
                externalId: undefined,
                name: 'Turkey',
                terms: {}
            },
            uae: {
                codename: 'uae',
                id: 'a18f55ac-2b85-4766-a249-12420ac610b5',
                externalId: undefined,
                name: 'UAE',
                terms: {}
            },
            uk___ireland_garden_tours: {
                codename: 'uk___ireland_garden_tours',
                id: 'd1610629-95cb-4b57-95bc-e15e70d002e9',
                externalId: undefined,
                name: 'UK & Ireland Garden Tours',
                terms: {}
            },
            usa: {
                codename: 'usa',
                id: '40ce36c5-9510-4512-970c-160acdcc4102',
                externalId: undefined,
                name: 'USA',
                terms: {}
            },
            uzbekistan: {
                codename: 'uzbekistan',
                id: '6eab9206-19ed-4741-b599-f33205e3261f',
                externalId: undefined,
                name: 'Uzbekistan',
                terms: {}
            },
            vietnam: {
                codename: 'vietnam',
                id: '27f3d099-8712-48b9-9998-098be7ef1fef',
                externalId: undefined,
                name: 'Vietnam',
                terms: {}
            },
            wales: {
                codename: 'wales',
                id: '438271db-0a05-4af0-a108-94dac4e5b5ce',
                externalId: undefined,
                name: 'Wales',
                terms: {}
            }
        }
    }
} as const;
